Hackalist/Hackalist.github.io

api/1.0/2015/04.json

Added stemhacks to your website!

Added stemhacks

---

api/1.0/2015/03.json

Updated hack the burgh

---

api/1.0/2015/04.json

There was an email sent to participants thet OwlHacks was postponed.

Owlhacks was postponed so removing it.

---

api/1.0/2015/04.json

Hack RU is clearly a 24 hour hackathon...

Add length for hack RU

---

index.html
js/app.js

Sorry for the large commit... It got a bit out of hand. While writing
this update I made sure not to change any of the functional or visual
aspects of the site, unless they were an obvious bug.
* Automatic API endpoint knowledge. Before when a new month was added it
had to be explicitly declared in the `js/app.js` file. Now the client
will get the apropriate data by polling.
* Simplify HTML. The HTML used to be a mass of repitition, using the
$scope.hackathons object I created from the first point I have
managed to minify the source so that it does not have to be repeated
per month
* Fix search bugs. I believe in the old sites their were a few one off
search bugs, I have fixed those with the new `applicable` filter

Refractor site, fix search bugs

---

api/1.0/2015/10.json
index.html
js/app.js

For #33.
Wow I killed my git history...

Fix toggling issues

---

index.html

Lets face it, the old toggle switches had a nice feel to them. I have
reverted the checkboxes, however rewrote the way their backend is
structured so it is a bit more logical. Instead of being represented by
a counter, it is being represented by a boolean, which is simply
inverted whenever the switch is clicked.

Add in old toggle switches

---

api/1.0/2015/09.json

Source: http://www.hackingeatingtracking.org/hackathon/

Add more information to Hacking Eating Tracking

---

index.html

The old version didn't really make sense, as we have our filters just
below...

Fix sub title

---

api/1.0/2015/10.json
css/style.css
index.html

Hey Everyone,
I added the new GitHub buttons addressed in #42  just under the 'Contribute to GitHub' button.
Rafe

Added GitHub Buttons to Fix #42

---

api/1.0/2015/09.json

Source: https://www.facebook.com/pennapps/photos/a.115146361876339.16135.103140939743548/926682837389350/?type=1&theater

Update PennApps XII host

---

js/app.js

Fix off-by-one bug

---

api/1.0/2015/10.json

India's Premier Student run Hackathon.

Added InOut

---

api/1.0/2015/11.json

Add CodeDay to 2015/11

---

api/1.0/2015/11.json

Added Codestellation

---

api/1.0/2015/11.json

Adding HackTrain

---

api/1.0/2015/11.json

Adding BathHack

---

api/1.0/2015/12.json

Adding HackKing's

---

api/1.0/2015/10.json

Adding FinTechathon

---

api/1.0/2015/11.json

Adding Apps World Hackathon by AngelHack

Adding Apps World Hackathon by AngelHack

---

api/1.0/2015/12.json

Added new hackathon for December 2015

Added techcrunch hackathon

---

api/1.0/2016/01.json

Add Hack Cambridge

---

api/1.0/2016/01.json

Added info for HackRice 2016 in January

HackRice 2016

---

api/1.0/2016/01.json

Update Location for Drexel University

Update Dragon Hacks Location

---

api/1.0/2016/01.json

Absurdly late notice, just realized our promotion guy hadn't submitted this

Add Valley Hackathon

---

api/1.0/2016/02.json

added HackLondon

---

api/1.0/2016/02.json

Added the [LAUNCH Hackathon](http://www.launchhackathon.com/)

[API] added LAUNCH Hackathon

---

api/1.0/2016/04.json

I spoke with the director of HackDFW this year, Adil Shaikh (https://github.com/anshaik), and the capacity for HackDFW this year will be 2000.

Update capacity for HackDFW

---

api/1.0/2016/04.json

Added QueensHack hackathon for the dates: 04/23 - 04/24

Added QueensHack

---

api/1.0/2016/05.json

Would appreciate you listing this upcoming hackathon!

Add GeoHackHSV Hackathon

---

api/1.0/2016/11.json

Just a quick fix for the broken HackOHI/O hackathon link.

Fix: HackOHI/O Link

---

api/1.0/2016/10.json

Adding HackUMass IV, which will be on Oct 7-9th.

Adding HackUMass IV to October

---

api/1.0/2016/10.json

HackHarvard 16 will be from October 21st-23rd

Added HackHarvard 16: Hack the Past

---

api/1.0/2016/10.json

Adding my university's hackathon - HackWestern 3
https://hackwestern.com

API update - Adding HackWestern 2016 to October 2016

---

api/1.0/2016/10.json

Added the TVCOG Cleantech Hackathon to the JSON file for Oct 2016.

TVCOG Cleantech Hackathon Addition

---

api/1.0/2016/10.json

added MIA Game Jam

---

api/1.0/2016/10.json

Add RevolutionUC at the University of Cincinnati 🎉  October 8 and 9!

Add RevolutionUC Fall 2016

---

api/1.0/2016/10.json

Contributed to https://github.com/Hackalist/Hackalist.github.io/issues/163

Adding upcoming hackathon in Sweden

---

api/1.0/2016/10.json

Added LNMHacks in October 2016

Added LNMHacks

---

api/1.0/2016/11.json

Added upcoming New Era Hackathon

---

api/1.0/2016/11.json

Added upcoming Expedition Hackathon

---

api/1.0/2016/10.json

Adding HackTX to October

---

api/1.0/2016/10.json

I'll let another maintainer look this over and merge it in.
On another note, we really need a quick way to automate adding in MLH hackathons. Do they have an API available?

Add hackMarist

---

api/1.0/2016/06.json

Adding ATX Hack for Change

---

api/1.0/2016/11.json

Added upcoming Ultrahack Hackathon

---

api/1.0/2016/12.json

LehighHacks is a hackathon that was shared on the MLH website

Added LehighHacks to list

---

api/1.0/2016/10.json

Added HackUPC to the list

---

api/1.0/2016/11.json

Added GreatUniHack and OxfordHack from MLH :)

Added GreatUniHack and OxfordHack

---

api/1.0/2017/02.json

Added hack@brown hackathon in February 2017.

Added hack@brown

---

api/1.0/2016/04.json

Added Ninja Hacks High School Hackathon April 2016

added Ninja Hacks

---

api/1.0/2017/01.json

Added McHacks

---

api/1.0/2016/10.json
api/1.0/2017/01.json

Fixed Typo + Added Invent:YU Israel #163

---

index.html

Hi! 
I don't know why but It looks like we were missing https:// for calling Google Analytics, I think? 
It was creating me the first error in Chrome and it made me unable to view the upcoming hackathons on Chrome!  
I tried to avoid all these fake changes other than me adding https:// to the file but couldn't do anything about it, is there a trick to avoid all these to detect change when there a nothing? 
Thanks!

Fixed missing https:// for Google Analytics

---

api/1.0/2016/11.json

Added Shiv Nadar University Hackathon

Added Shiv Nadar University Hackathon

---

api/1.0/2016/11.json
api/1.0/2016/12.json

Added Bothack Berlin and Medical Internet of Things Hackathons

Added Bothack Berlin and Medical Internet of Things Hackathon

---

api/1.0/2017/02.json

Add BrickHack

---

api/1.0/2016/02.json

the @WolfBeacon team at work! Gotta keep the API consisten else the code's gonna crash :P
cc @paked

Added missing GooglePlusURL

---

api/1.0/2016/06.json

Changed Jun to June

---

api/1.0/2017/03.json

Added ClashHacks 2017 in the list.

ClashHacks added

---

api/1.0/2017/04.json

Add RevolutionUC at the University of Cincinnati 🎉 April 8 and 9! ⚡️

Add RevolutionUC Spring 2017

---

api/1.0/2017/04.json

Add HackHunterdon on April 28-29, 2017

---

api/1.0/2017/03.json

AUHack is a MLH hackathon happening in Aarhus, Denmark.

Add AUHack '17 to March Calendar

---

api/1.0/2017/03.json

Please try and keep the data consistent, our parser crashed due to this.

Added length to Virtual2Reality which crashed parser

---

api/1.0/2017/08.json

Adding WebHacks to the list of hackathons in August.

Adding WebHacks

---

api/1.0/2017/10.json

add thacks 2 to json file of October hackathons

add thacks

---

api/1.0/2017/11.json

Adding [Hack K-State 2017 ](https://hackkstate.tech/) hackathon for November

Hack K-State 2017 for November

---

api/1.0/2017/09.json

Add Hack for Savannah on 9/22-9/24

---

api/1.0/2018/02.json

I'm just adding Hack the Hammer. I don't know why Hack the Valley is recognized as an entire deletion, but that wasn't changed at all.

Adding Hack the Hammer

---

api/1.0/2018/03.json

Create March file - 03.json 📁 
Add HackFSU hackathon to the 2018 hackathons for March 🏖 
Ran the content through the JSONLint for validation ✅
🎉

Create March list and add HackFSU to the list

---

api/1.0/2018/01.json

Add SheHacks hackathon to the 2018 hackathons for January 💪 
Ran the content through the JSONLint for validation ✅
🎉

Add SheHacks to January list of 2018 hackathons

---

api/1.0/2017/11.json

Add TecmiHacks hackathon to the 2017 hackathons for November
Ran the content through the JSONLint for validation ✅
🎉

Add TecmiHacks to November list of 2017 events

---

api/1.0/2017/11.json

#357 
Resolves what I believe is a request for an addition to the Nov. 2017 file:
Added AutoMobility LA's hackathon information to 11/17 json file

AutoMobility LA added to Nov. json file

---

api/1.0/2018/01.json

SB Hacks IV takes place January 19 - 21, 2018.

Added SB Hacks IV

---

api/1.0/2018/03.json

Add RevolutionUC at the University of Cincinnati 🎉  - March 3rd and 4th!
⚡️

Add RevolutionUC Spring 2018

---

api/1.0/2018/01.json
api/1.0/2018/02.json

Move MAHacks date from Jan 13 to Feb 24

---

api/1.0/2018/04.json

Hackathon happening in Edinburgh April 7/8. I've checked test.js on my machine and I'm happy with how it appears when I visit the index page.

Add CreatED - Hardware Hackathon

---

api/1.0/2018/04.json

Added hackital ethereum 2018

---

api/1.0/2018/06.json

Not sure what's the process if the json doesn't exist yet, so I just created a new one, let me know if I did anything wrong. :)

Add HackPrague 2018 / June

---

api/1.0/2018/07.json

High School Status was not updated

Update 07.json for Hackademia

---

api/1.0/2018/10.json

Add Hackathon Download Innovation 2018 in Bergamo, Italy

Add Hackathon Download Innovation 2018

---

api/1.0/2018/10.json

Hi guys! Could you include our Wide Open Source Science hackathon?

Wide Open Source Science hackathon

---

api/1.0/2018/10.json

Add entry for the Huntsville Space Apps Challenge.

International 2018 NASA Space Apps - Huntsville

---

api/1.0/2018/11.json

Updated 11.json

---

api/1.0/2019/01.json

CyberCup is the annual socio-tech festival of Amity University, Noida curated on behalf of the Department of Computer Science of Amity School of Engineering and Technology.
This time it is organising a hackathon.

Added Cyber Cup Hackathon

---

api/1.0/2019/02.json

Added HackCU V: http://hackcu.org in Boulder, CO.

added HackCU Feb 2019

---

api/1.0/2019/03.json

Added "WhatTheHack Belgium 2019"

Added "WhatTheHack  Belgium 2019"

---

api/1.0/2019/01.json

Hack36 is the annual student hackathon of MNNIT, Allahabad.

Added Hack36

---

api/1.0/2019/03.json

Add RevolutionUC 2019

---

api/1.0/2019/04.json

Here we go! 🎉
The event date has been revised from February to April.

Add LaunchHacks 2019

---

api/1.0/2019/04.json

Add Smart Mobility Hackathon 2019

Smart Mobility Hackathon 2019

---

api/1.0/2019/03.json

Feel to contact us using the information on our website: denalihacks.com.

Add Denali Hacks to March, 2019

---

api/1.0/2019/03.json

Add the Hackathon for safetydays 2019 (www.safetydays.de)

Add safety days 2019

---

api/1.0/2019/09.json

https://dohack.io - Application is open :)

Add DO!Hack2019

---

api/1.0/2019/06.json
api/1.0/2019/07.json
api/1.0/2019/08.json

added BreakTheFake Hackathon 2019 Jakarta , KL and Manila leg. happen on 3 separate dates

added BreakTheFake Hackathon

---

api/1.0/2019/10.json

Added [InOut 6.0](https://hackinout.co) to the list.

Added InOut 6.0 to the list.

---

api/1.0/2019/10.json

Updated the duration of InOut 6.0 hackathon to match the correct duration.

Updated InOut 6.0 Hackathon duration.

---

api/1.0/2020/04.json

thanks for the initiative - added our event for April. please contact me at florian@feichtinger.co if you have any comments. Cheers Florian

Pull hrhackathon2020

---

api/1.0/2020/04.json

Lmk if there's anything needed to be changed.
Thanks!

Add Stop COVID-19 hackathon

---

api/1.0/2020/04.json

Reverts Hackalist/Hackalist.github.io#510

Revert "Add Stop COVID-19 hackathon"

---

api/1.0/2020/05.json

Lmk if there's anything needed to be changed

Add New York Blockchain Week 

---

api/1.0/2020/05.json

Added "Palette" (Design Hackathon)

Updated 05.json

---

api/1.0/2020/05.json

Lmk if there's anything needed to be changed

Add GitxChange hackathon

---

api/1.0/2020/07.json

hope everything is formatted properly, let me know if there are issues! 🙏

Add HackFS by ETHGlobal & Protocol Labs

---

api/1.0/2020/07.json

lmk if there's anything needed to be changed

Add Open web incubator

---

api/1.0/2020/10.json
api/1.0/2020/11.json

@rodrigoargumedo Does this PR look good?

Add gitcoin events for october and november

---

api/1.0/2021/02.json

As mentioned here: https://organize.mlh.io/participants/events/6397-impractical-hackers

Say that Impractical Hackers allows high schoolers

---

api/1.0/2021/03.json

Yahoo Hack Together, March 21-28, Global, Virtual, opensource hackathon, Swag for participating, www.yahoo.com/hacktogether

Adding Yahoo Hack Together

---

api/1.0/2021/04.json

Add Hack36

---

api/1.0/2021/03.json

Add MOZOHACK 2.1

---

api/1.0/2021/03.json

* fixed broken links
* updated dates for the event

fix: links and dates fixed

---

api/1.0/2021/05.json

The SPARC program is supported by the NIH Common Fund to accelerate development of therapeutic devices and identification of neural targets for bioelectronic medicine—modulating electrical activity in nerves to help treat diseases and conditions, such as hypertension and gastrointestinal disorders, by precisely adjusting organ function.

Add SPARC codeathon

---

api/1.0/2022/08.json

Adding RocketPy Hackathon 2022 in the list!
https://www.youtube.com/watch?v=lEywDzxwM4s&t=714s

Adding RocketPy Hackathon 2022 in the list!

---

api/1.0/2022/09.json

Future of Healthcare Hackathon by Datavant

Add Future of Healthcare Hackathon by Datavant

---

api/1.0/2023/03.json

I would like to add our new hackathon here.

ICRA 2023 wrestling

---

api/1.0/2023/09.json

Add Actaully Open AI Hackathon

---

api/1.0/2024/01.json

PEC Hacks, a 36-hours hackathon in Chennai, India added.

Added PEC Hacks
